---
name: upload_coverage_report

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  upload_coverage_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: "1.10.3.1029"

      - name: Run tests
        run: |
          clojure -X:coverage

      - name: Upload coverage to codecov (tokenless)
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
        uses: codecov/codecov-action@v4
        with:
          files: "target/coverage/codecov.json"
          fail_ci_if_error: true

      - name: Upload coverage to codecov (with token)
        if: "! github.event.pull_request.head.repo.fork "
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "target/coverage/codecov.json"
          fail_ci_if_error: true
...
